#dockerfile.rails
FROM ruby:3.0.2

#install rails
ENV INSTALL_PATH /opt/app
RUN mkdir -p $INSTALL_PATH

# Install rails
RUN gem install rails bundler

# Run chown -R user:user /opt/app
WORKDIR /opt/app
# Run a shell
CMD ["/bin/sh"]