FROM node:14-alpine

# Set working directory
WORKDIR /app

# Insall dependencies for the bacckend and the frontend
COPY package*.json ./
RUN npm install --prefix client && npm install

# Copy the rest of the application code
COPY . .

# Build the React app
RUN npm run build --prefix client

# Start the web server
CMD ["npm", "start"]